### ISSUE TITLE
Netlifyビルド時間短縮

### ISSUE THREAD

**Issue by kou029w** [tottori-covid19/covid19#8]
## 改善詳細 / Details of Improvement
- Netlifyビルド時間短縮
- 現在一回あたり5-8分程度かかる
- すでにこの3日間でStarter Planの約半分 150  build minites程度使っており、このままだと利用困難になるおそれがあるので修正したい
- 多言語対応を減らしたりGitHub Actionsと併用するなど工夫すれば対応できるはず 
- 面倒なら課金するのも手かなと思っている

**Comment by Tiryoh** [comment]
はじめまして。
こちらのGitHub Actionsはいかがでしょうか。
https://github.com/nwtgck/actions-netlify
もしよければPRにてご協力します。

**Comment by kou029w** [comment]
@Tiryoh さん、ありがとうございます!
取り急ぎNetlifyに私のクレジットカード情報は入れておいたので緊急性はありません
もしご協力していただけるならとてもうれしいです! (おもに私のお財布がw)

**Comment by kou029w** [comment]
nwtgck/actions-netlify 特に異論ありません。
良さそうですね!
